"""One worldline-day of observation.

Advances the chain a single step, writes the readout, and emits that many
commits. Run daily. It is idempotent per date, because a scheduled workflow
that fires twice should not double-count a day.
"""
from __future__ import annotations

import argparse
import random
import subprocess
import sys
from datetime import date, datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from divergence import (EPOCH, FIELD_NAME, FIELD_POSTURE, SEED,
                        STEINS_GATE_THRESHOLD, run_chain)
from dmail import compose

ROOT = Path(__file__).resolve().parent.parent
READOUT_PATH = ROOT / "DIVERGENCE.md"

OWNERS = ["Hououin Kyouma", "Leslie Knope", "Ben Wyatt", "Jerry Gergich",
          "Makise Kurisu", "Ron Swanson", "Chris Traeger", "Itaru Hashida"]


def nixie(value: float) -> str:
    digits = f"{value:.6f}"
    top = "".join("┌─┐" for _ in digits)
    mid = "".join(f"│{d}│" for d in digits)
    bot = "".join("└─┘" for _ in digits)
    return f"    {top}\n    {mid}\n    {bot}"


def readout(day: date, field: int, divergence: float, count: int,
            emitted: int, rng: random.Random) -> str:
    field_label = FIELD_NAME[field]
    if divergence >= STEINS_GATE_THRESHOLD:
        field_label = "Steins;Gate"
    delta = lambda: rng.choice("▲▼─")
    rows = [
        ("Worldline Divergence", f"{divergence:.6f}"),
        ("Synergy Coefficient (name subject to change)", f"{rng.uniform(0.6, 0.99):.2f}"),
        ("Stakeholder Alignment Index", f"{rng.uniform(1, 10):.1f}"),
        ("Ideation Throughput", f"{count} story points"),
        ("Bandwidth Utilisation", f"{rng.uniform(70, 140):.0f}%"),
        ("Lil Sebastian Sentiment", "5,000 candles"),
    ]
    table = "\n".join(
        f"| {name} | {value} | {delta()} | {rng.choice(OWNERS)} |" for name, value in rows)
    return f"""# Divergence Meter

{nixie(divergence)}

**Attractor field:** {field_label}
**Operating posture:** {FIELD_POSTURE[field]}
**Observation window:** {day.isoformat()}
**Observations this cycle:** {emitted} of {count}

## Key Performance Indicators

| Indicator | Reading | WoW | Owner |
|---|---|---|---|
{table}

Ideation Throughput is this cycle's commit count with a different name on it.
Every other row is a random number. No decisions were informed by this document.

Generated by the Future Gadget Laboratory. El psy kongroo.
"""


def git(*args: str) -> None:
    subprocess.run(["git", *args], cwd=ROOT, check=True,
                   stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--date", type=date.fromisoformat, default=None,
                    help="sample a specific calendar day; does not backdate the commit")
    args = ap.parse_args()

    today = args.date or datetime.now(timezone.utc).date()
    if today < EPOCH:
        print(f"{today} precedes the epoch. This worldline does not exist yet.")
        return 0

    # Reading Steiner: the chain holds no stored state, so the lab replays the
    # entire worldline from the epoch on every run to recover its place in it.
    # Deterministic, which means simulate.py shows exactly what will happen.
    day, count, field, divergence, citation = list(
        run_chain(EPOCH, (today - EPOCH).days + 1, seed=SEED))[-1]

    if citation:
        print(f"convergence point: {citation}")

    # A zero day must emit nothing at all. Committing anything here, even a
    # state file, greens the square and erases the gap the model just produced.
    if count == 0:
        print(f"{today}  {FIELD_NAME[field]} field, 0 observations. "
              "Actively working to reduce this department's output.")
        return 0

    rng = random.Random(f"{today}:{divergence}")
    print(f"{today}  {FIELD_NAME[field]} field, {count} observations")
    for i in range(1, count + 1):
        report = readout(day, field, divergence, count, i, rng)
        message = compose(field, rng)
        print(f"  {message.splitlines()[0]}")
        if not args.dry_run:
            READOUT_PATH.write_text(report)
            git("add", "DIVERGENCE.md")
            git("commit", "-m", message,
                "-m", f"Divergence: {divergence:.6f}\nEl-Psy-Kongroo: true")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
